apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregatorservice-common
  namespace: easytrade-ocp
data:
  NODE_ENV: "production"
  OFFER_SERVICE: "offerservice:8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregatorservice-1
  namespace: easytrade-ocp
data:
  PLATFORM: "dynatestsieger.at"
  STARTER_PACKAGE_PROBABILITY: "0.6"
  LIGHT_PACKAGE_PROBABILITY: "0.3"
  PRO_PACKAGE_PROBABILITY: "0.1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregatorservice-2
  namespace: easytrade-ocp
data:
  PLATFORM: "tradeCom.co.uk"
  STARTER_PACKAGE_PROBABILITY: "0.8"
  LIGHT_PACKAGE_PROBABILITY: "0.2"
  PRO_PACKAGE_PROBABILITY: "0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregatorservice-3
  namespace: easytrade-ocp
data:
  PLATFORM: "CryptoTrading.com"
  FILTER: '["Crypto"]'
  MAXFEE: "0"
  STARTER_PACKAGE_PROBABILITY: "0.5"
  LIGHT_PACKAGE_PROBABILITY: "0.4"
  PRO_PACKAGE_PROBABILITY: "0.1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregatorservice-4
  namespace: easytrade-ocp
data:
  PLATFORM: "CheapTrading.mi"
  MAXFEE: "0"
  STARTER_PACKAGE_PROBABILITY: "1"
  LIGHT_PACKAGE_PROBABILITY: "0"
  PRO_PACKAGE_PROBABILITY: "0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregatorservice-5
  namespace: easytrade-ocp
data:
  PLATFORM: "Stratton-oakmount.com"
  FILTER: '["Shares"]'
  STARTER_PACKAGE_PROBABILITY: "0"
  LIGHT_PACKAGE_PROBABILITY: "0.1"
  PRO_PACKAGE_PROBABILITY: "0.9"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregatorservice
  namespace: easytrade-ocp
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: aggregatorservice
  template:
    metadata:
      labels:
        app: aggregatorservice
    spec:
      serviceAccountName: easytrade-sa
      containers:
        - name: aggregatorservice-1
          image: &image gcr.io/dynatrace-demoability/easytrade/aggregatorservice:a9edfaf
          envFrom:
            - configMapRef:
                name: aggregatorservice-common
            - configMapRef:
                name: aggregatorservice-1
          resources: &default_res
            requests:
              cpu: 25m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: true
        - name: aggregatorservice-2
          image: *image
          envFrom:
            - configMapRef:
                name: aggregatorservice-common
            - configMapRef:
                name: aggregatorservice-2
          resources: *default_res
          securityContext:
            allowPrivilegeEscalation: true
        - name: aggregatorservice-3
          image: *image
          envFrom:
            - configMapRef:
                name: aggregatorservice-common
            - configMapRef:
                name: aggregatorservice-3
          resources: *default_res
          securityContext:
            allowPrivilegeEscalation: true
        - name: aggregatorservice-4
          image: *image
          envFrom:
            - configMapRef:
                name: aggregatorservice-common
            - configMapRef:
                name: aggregatorservice-4
          resources: *default_res
          securityContext:
            allowPrivilegeEscalation: true
        - name: aggregatorservice-5
          image: *image
          envFrom:
            - configMapRef:
                name: aggregatorservice-common
            - configMapRef:
                name: aggregatorservice-5
          resources: *default_res
          securityContext:
            allowPrivilegeEscalation: true
