apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculationservice
  namespace: easytrade-ocp
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: calculationservice
  template:
    metadata:
      labels:
        app: calculationservice
        persistence: ephemeral
    spec:
      serviceAccountName: easytrade-sa
      containers:
        - name: calculationservice
          image: gcr.io/dynatrace-demoability/easytrade/calculationservice:a9edfaf
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
          securityContext:
            allowPrivilegeEscalation: true
