apiVersion: v1
kind: ConfigMap
metadata:
  name: connection-strings
  namespace: easytrade-ocp
data:
  JAVA_CONNECTION_STRING: jdbc:sqlserver://easytrade-ocp-db:1433;database=TradeManagement;user=sa;password=yourStrong(!)Password;encrypt=false;trustServerCertificate=false;loginTimeout=30;
  DOTNET_CONNECTION_STRING: Data Source=easytrade-ocp-db;Initial Catalog=TradeManagement;Persist Security Info=True;User ID=sa;Password=yourStrong(!)Password;TrustServerCertificate=true
  GO_CONNECTION_STRING: sqlserver://sa:yourStrong(!)Password@easytrade-ocp-db:1433?database=TradeManagement&connection+encrypt=false&connection+TrustServerCertificate=false&connection+loginTimeout=30
