apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: easytrade-ocp
  labels:
    app: frontend
    dt.owner: easytrade-devops
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        persistence: ephemeral
        dt.owner: easytrade-devops
    spec:
      containers:
        - name: frontend
          image: gcr.io/dynatrace-demoability/easytrade/frontend:a9edfaf
          env:
            - name: DT_RELEASE_PRODUCT
              valueFrom:
                configMapKeyRef:
                  name: versioning
                  key: PRODUCT
            - name: DT_RELEASE_STAGE
              valueFrom:
                configMapKeyRef:
                  name: versioning
                  key: STAGE
            - name: DT_RELEASE_BUILD_VERSION
              valueFrom:
                configMapKeyRef:
                  name: versioning
                  key: BUILD_VERSION
            - name: DT_RELEASE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: versioning
                  key: RELEASE_VERSION
            - name: DT_CUSTOM_PROP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['dt.owner']
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: easytrade-ocp
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
