apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: headlessloadgen
  name: headlessloadgen
  namespace: easytrade-ocp
spec:
  selector:
    matchLabels:
      app: headlessloadgen
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: headlessloadgen
    spec:
      serviceAccountName: easytrade-sa
      containers:
        - name: headlessloadgen
          image: gcr.io/dynatrace-demoability/headlessloadgen:b554e03
          imagePullPolicy: Always
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              #cpu: "500m"
          env:
            - name: EASY_TRADE_DOMAIN
              value: easytrade-ocp-frontend-reverseproxy
            - name: EASY_TRADE_PORT
              value: "80"
            - name: NODE_LOG_LEVEL
              value: "info"
          securityContext:
            allowPrivilegeEscalation: true
