apiVersion: apps/v1
kind: Deployment
metadata:
  name: third-party-service
  namespace: easytrade-ocp
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: third-party-service
  template:
    metadata:
      labels:
        app: third-party-service
        persistence: ephemeral
    spec:
      containers:
        - name: third-party-service
          image: gcr.io/dynatrace-demoability/easytrade/third-party-service:a9edfaf
          ports:
            - containerPort: 8080
          env:
            - name: CREDIT_CARD_ORDER_SERVICE_HOSTANDPORT
              value: "credit-card-order-service:8080"
            - name: PROXY_PREFIX
              value: "third-party-service"
            - name: COURIER_DELAY
              value: "400"
            - name: COURIER_RATE
              value: "900"
            - name: MANUFACTURE_DELAY
              value: "500"
            - name: MANUFACTURE_RATE
              value: "900"
            - name: DT_RELEASE_PRODUCT
              valueFrom:
                configMapKeyRef:
                  name: versioning
                  key: PRODUCT
            - name: DT_RELEASE_STAGE
              valueFrom:
                configMapKeyRef:
                  name: versioning
                  key: STAGE
            - name: DT_RELEASE_BUILD_VERSION
              valueFrom:
                configMapKeyRef:
                  name: versioning
                  key: BUILD_VERSION
            - name: DT_RELEASE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: versioning
                  key: RELEASE_VERSION
          envFrom:
            - configMapRef:
                name: feature-flag-service-setup
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: third-party-service
  namespace: easytrade-ocp
spec:
  type: ClusterIP
  selector:
    app: third-party-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
