---
apiVersion: v1
kind: ConfigMap
metadata:
  name: versioning
  namespace: easytrade-ocp
data:
  BUILD_VERSION: jz115zu
  RELEASE_VERSION: demo-bad-release
  STAGE: prod
  PRODUCT: easytrade
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-service
  namespace: easytrade-ocp
  labels:
    app: broker-service
    dt.owner: easytrade-devops
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: broker-service
  template:
    metadata:
      labels:
        app: broker-service
        persistence: ephemeral
        dt.owner: easytrade-devops
    spec:
      serviceAccountName: easytrade-sa
      containers:
        - name: broker-service
          image: popecruzdt/easytrade-brokerservice:jz115zu
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: broker-service-envs
            - configMapRef:
                name: feature-flag-service-setup
          env:
            - name: MSSQL_CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: connection-strings
                  key: DOTNET_CONNECTION_STRING
            - name: DT_RELEASE_PRODUCT
              valueFrom:
                configMapKeyRef:
                  name: versioning
                  key: PRODUCT
            - name: DT_RELEASE_STAGE
              valueFrom:
                configMapKeyRef:
                  name: versioning
                  key: STAGE
            - name: DT_RELEASE_BUILD_VERSION
              valueFrom:
                configMapKeyRef:
                  name: versioning
                  key: BUILD_VERSION
            - name: DT_RELEASE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: versioning
                  key: RELEASE_VERSION
            - name: DT_CUSTOM_PROP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['dt.owner']
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
          securityContext:
            allowPrivilegeEscalation: true
