apiVersion: apps/v1
kind: Deployment
metadata:
  name: pricing-service
  namespace: easytrade-ocp
  labels:
    app: pricing-service
    dt.owner: easytrade-devops
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: pricing-service
  template:
    metadata:
      labels:
        app: pricing-service
        persistence: ephemeral
        dt.owner: easytrade-devops
    spec:
      containers:
        - name: pricing-service
          image: popecruzdt/easytrade-pricingservice:jz115zu
          ports:
            - containerPort: 8080
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_USER
              value: "userxxx"
            - name: RABBITMQ_PASSWORD
              value: "passxxx"
            - name: RABBITMQ_QUEUE
              value: "Trade_Data_Raw"
            - name: PROXY_PREFIX
              value: "pricing-service"
            - name: MSSQL_CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: connection-strings
                  key: GO_CONNECTION_STRING
            - name: DT_RELEASE_PRODUCT
              valueFrom:
                configMapKeyRef:
                  name: versioning
                  key: PRODUCT
            - name: DT_RELEASE_STAGE
              valueFrom:
                configMapKeyRef:
                  name: versioning
                  key: STAGE
            - name: DT_RELEASE_BUILD_VERSION
              valueFrom:
                configMapKeyRef:
                  name: versioning
                  key: BUILD_VERSION
            - name: DT_RELEASE_VERSION
              valueFrom:
                configMapKeyRef:
                  name: versioning
                  key: RELEASE_VERSION
            - name: DT_CUSTOM_PROP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['dt.owner']
          resources:
            requests:
              cpu: 25m
              memory: 100Mi
            limits:
              memory: 150Mi
---
apiVersion: v1
kind: Service
metadata:
  name: pricing-service
  namespace: easytrade-ocp
spec:
  type: ClusterIP
  selector:
    app: pricing-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
