---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: springio-scc
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- default
- springio-sa
