---
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: easytrade-scc
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- default
- easytrade-sa